services:
  web:
    build:
      context: ../apps/fibonacci/client
      dockerfile: ../../../docker/FibClient.Dockerfile.dev
      tags:
        - thomascode92/fib-client-dev
    volumes:
      - /usr/app/node_modules
      - ../apps/fibonacci/client:/usr/app
    ports:
      - 3000:5173
