services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  gateway:
    build:
      dockerfile: Dockerfile.dev
      context: ./gateway
    ports:
      - 8080:80
    restart: always
    depends_on:
      - client
      - api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - ./env/.server.env
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
