name: Test, Build and Deploy a React App
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/fibonacci/client/**'
      - .github/workflows/react-app.yml
  push:
    branches:
      - main
    paths:
      - 'apps/fibonnaci/client/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -f ./docker/FibClient.Dockerfile.dev -t fib-client ./apps/fibonacci/client/
      - name: Run Tests
        run: docker run -e CI=true fib-client npm run test
